# Generated by Django 2.2.10 on 2020-02-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(max_length=2)),
                ('cover_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ISBN_10', 'ISBN_10'), ('ISBN_13', 'ISBN_13'), ('ISSN', 'ISSN'), ('OTHER', 'OTHER')], max_length=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker_app.Book')),
            ],
        ),
    ]
