# Generated by Django 2.2.10 on 2020-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker_app', '0002_auto_20200215_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='type',
            field=models.CharField(blank=True, choices=[('ISBN_10', 'ISBN_10'), ('ISBN_13', 'ISBN_13'), ('ISSN', 'ISSN'), ('OTHER', 'OTHER')], max_length=7),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
