# Generated by Django 2.2.10 on 2020-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker_app', '0003_auto_20200216_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
