# Generated by Django 2.2.10 on 2020-02-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker_app', '0004_auto_20200216_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
