# Generated by Django 2.2.10 on 2020-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker_app', '0005_auto_20200217_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
